### PR TITLE
Remove .decode method calls on strings in plugins

### PR DESCRIPTION
**Pull request by raharper**
Running under python3 and using plugins.add_string_as_file
and the plugins._collect_strings() methods both attempt to
decode a string which produces this backtrace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'

Remove the .decode as it's not needed in python3.

Signed-off-by: Ryan Harper <ryan.harper@canonical.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
We need to make sure that this works with Python 2.7.x as well

**Comment by bmr-cymru** [comment]
As well as needing to work with all supported versions of the runtime the patch also needs to follow the [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines).

The patch is also incomplete in that `string.decode()` is used in other parts of the tree - both the archive and utilities modules also use this method.

**Comment by bmr-cymru** [comment]
Closing this out as it's not clear what the problem was - please file an issue & describe any problems you're seeing along with a complete backtrace and information on the python runtime version if you're seeing any character encoding bugs.
