### ISSUE TITLE
3.6 regression - systemd plugin fails

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1373]
sos_logs/systemd-plugin-errors.txt
Traceback (most recent call last):
  File "/home/bryan/git/sos/sos/sosreport.py", line 1088, in collect_plugin
    plug.collect()
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 947, in collect
    self._collect_copy_specs()
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 905, in _collect_copy_specs
    self._do_copy_path(path)
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 435, in _do_copy_path
    self._copy_dir(srcpath)
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 381, in _copy_dir
    self._do_copy_path(os.path.join(srcpath, afile), dest=None)
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 431, in _do_copy_path
    self._copy_symlink(srcpath)
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 366, in _copy_symlink
    self._do_copy_path(self.strip_sysroot(absdest))
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 443, in _do_copy_path
    self._copy_node(srcpath, st)
  File "/home/bryan/git/sos/sos/plugins/__init__.py", line 406, in _copy_node
    self.archive.add_node(path, mode, os.makedev(dev_maj, dev_min))
  File "/home/bryan/git/sos/sos/archive.py", line 330, in add_node
    dest = self._check_path(path, P_NODE)
  File "/home/bryan/git/sos/sos/archive.py", line 224, in _check_path
    if path_type == P_NODE and not is_special(st.st_mode):
  File "/home/bryan/git/sos/sos/archive.py", line 206, in is_special
    stat.ISBLK(mode),
AttributeError: module 'stat' has no attribute 'ISBLK'

**Comment by BryanQuigley** [comment]
(or errors, out still collects other data)

**Comment by BryanQuigley** [comment]
Bisected to 7d098d89e509af9cbd3748bbae0fd3e1cf4df771, which makes sense as it introduced the code.
